##! /usr/bin/python
__author__ = 'Zach Dischner'
__copyright__ = "NA"
__credits__ = ["NA"]
__license__ = "NA"
__version__ = "0.0.1"
__maintainer__ = "Zach Dischner"
__email__ = "zach.dischner@gmail.com"
__status__ = "Dev"

"""
File name: Defines.py
Authors: Zach Dischner
Created: 7/18/2014
Modified: 7/18/2014

This module just has a bunch of defines in it in an attempt not to clutter up the main processing module

Todos:

"""

TLCColumns = ['VE__SUMM_ENC_PHASE',
             'VE__SUMM_VE',
             'VE__SUMM_VISIT_ABSSTART',
             'VE__SUMM_VISIT_DOYSTART',
             'VE__SUMM_VISIT_START',
             'VE__SUMM_VISIT_NAME',
             'VE__SUMM_SE_NAME',
             'VE__SUMM_SAP_NAME',
             'VE__SUMM_SAP_DBID',
             'VE__SUMM_INSTRUMENT',
             'VE__SUMM_MODE',
             'VE__SUMM_TARGET',
             'VE__SUMM_GC',
             'VE__SUMM_MT_LIST',
             'VE__SUMM_ERR_MSG',
             'VE__GNL_PAD',
             'VE__GNL_SETUP',
             'VE__GNL_START_TIME',
             'VE__GNL_DURATION',
             'VE__GNL_WRAPUP',
             'VE__GNL_N_ALONG_TRACK',
             'VE__GNL_N_ACROSS_TRACK',
             'VE__GNL_N_PER_POINTING',
             'VE__GNL_N_ALONG_REQ',
             'VE__GNL_N_ACROSS_REQ',
             'VE__GNL_RAWSSR_GBIT',
             'VE__GNL_TARGET_RANGE',
             'VE__GNL_EXP_TIME',
             'VE__GNL_RESN',
             'VE__GNL_SOLPHASE',
             'VE__VISIT_DESCRIPTION',
             'VE__VISIT_COMMENTS',
             'VE__TIME_VE',
             'VE__TIME_OFFSET',
             'VE__TIME_SETUP_START',
             'VE__TIME_SETUP_END',
             'VE__TIME_SETUP_DUR',
             'VE__TIME_SETUP_SSR',
             'VE__TIME_SETUP_INSTR',
             'VE__TIME_SETUP_GC',
             'VE__TIME_OBS_START',
             'VE__TIME_OBS_END',
             'VE__TIME_OBS_DUR',
             'VE__TIME_WRAP_START',
             'VE__TIME_WRAP_END',
             'VE__TIME_WRAP_DUR',
             'VE__TIME_START_TIME',
             'VE__TIME_DURATION',
             'VE__ERR_N_RED',
             'VE__ERR_N_YELLOW',
             'VE__ERR_MSG',
             'VE__SCIPLAN_VER',
             'VE__ID_VE_INDEX',
             'VE__ID_VISIT_INDEX',
             'VE__ID_SE_INDEX',
             'VE__ID_SE_SEQUENCE',
             'VE__ID_SE_MASTER_ID',
             'VE__INSTR_VE',
             'VE__INSTR_NAME',
             'VE__INSTR_MODE',
             'VE__INSTR_TYPE',
             'VE__TARGET_VE',
             'VE__TARGET_NAME',
             'VE__TARGET_TYPE',
             'VE__TARGET_SPICE_CODE',
             'VE__TARGET_RA_DEG',
             'VE__TARGET_DEC_DEG',
             'VE__OCTARGET_NAME',
             'VE__OCTARGET_TYPE',
             'VE__OCTARGET_SPICE_CODE',
             'VE__OCTARGET_RA_DEG',
             'VE__OCTARGET_DEC_DEG',
             'VE__BORESIGHT_NAME',
             'VE__BORESIGHT_APPROX',
             'VE__BORESIGHT_VALID',
             'VE__BORESIGHT_ALT',
             'VE__BORESIGHT_AZ',
             'VE__GC_VE',
             'VE__GC_TYPE',
             'VE__GC_N_ALONG_TRACK',
             'VE__GC_N_ACROSS_TRACK',
             'VE__GC_N_PER_POINTING',
             'VE__GC_NTOT_PER_POINTING',
             'VE__GC_N_ALONG_REQ',
             'VE__GC_N_ACROSS_REQ',
             'VE__GC_EXP_TIME',
             'VE__GC_IMAGE_DT',
             'VE__GC_ALONG_DT_MIN',
             'VE__GC_ALONG_DT_PAD',
             'VE__GC_ALONG_DT',
             'VE__GC_ACROSS_DT_MIN',
             'VE__GC_ACROSS_DT_PAD',
             'VE__GC_ACROSS_DT',
             'VE__GC_ALONG_OVERLAP_MIN',
             'VE__GC_ALONG_OVERLAP',
             'VE__GC_ALONG_OFFSET',
             'VE__GC_ACROSS_OVERLAP_MIN',
             'VE__GC_ACROSS_OVERLAP',
             'VE__GC_ACROSS_OFFSET',
             'VE__AXIS_VALID',
             'VE__AXIS_RATE',
             'VE__AXIS_TYPE',
             'VE__AXIS_APPROX',
             'VE__OBSDB_VE',
             'VE__OBSDB_NUM',
             'VE__OBSDB_DBNAME',
             'VE__OBSDB_ATTDB',
             'VE__OBSDB_RATENAME',
             'VE__OBSDB_RATE',
             'VE__OBSDB_VALID',
             'VE__FOV_VE',
             'VE__FOV_ALONG_IFOV',
             'VE__FOV_ACROSS_IFOV',
             'VE__FOV_ALONG',
             'VE__FOV_ACROSS',
             'VE__FOV_VALID',
             'VE__CDH_VE',
             'VE__CDH_SMOOTH',
             'VE__CDH_SSR_FACTOR',
             'VE__CDH_IMAGE_DT_MIN',
             'VE__CDH_BITS_PER_N',
             'VE__CDH_N_DEF',
             'VE__CDH_POINTING_DT_DEF',
             'VE__CDH_FRACSEC',
             'VE__CDH_SECTORS_PER_N',
             'VE__CDH_EXP_TIME',
             'VE__CDH_N_TDI',
             'VE__CDH_LOW_SPEED_RATE_DEF',
             'VE__CDH_HIGH_SPEED_RATE_DEF',
             'VE__GEOM_VE',
             'VE__GEOM_MID_TIME',
             'VE__GEOM_MID_DATETIME',
             'VE__GEOM_MID_DOYTIME',
             'VE__GEOM_TARGET_TYPE',
             'VE__GEOM_TARGET_RADIUS_NOM',
             'VE__GEOM_TARGET_RADIUS_PAD',
             'VE__GEOM_TARGET_RADIUS',
             'VE__GEOM_TARGET_FRACTION',
             'VE__GEOM_JUST_SUNLIT',
             'VE__GEOM_POINTING_CONTROL',
             'VE__GEOM_TARGET_RANGE',
             'VE__GEOM_SOLPHASE',
             'VE__GEOM_OPNAV_SIGMA',
             'VE__GEOM_ORBNORM_ERR_HW_KM',
             'VE__GEOM_PROJVEL_ERR_HW_KM',
             'VE__GEOM_ROLL_ANGLE',
             'VE__GEOM_ACROSS_ERR_HW_KM',
             'VE__GEOM_ALONG_ERR_HW_KM',
             'VE__GEOM_RADIAL_ERR_HW_KM',
             'VE__GEOM_POINTING_ERR_HW_KM',
             'VE__GEOM_ACROSS_FW',
             'VE__GEOM_ALONG_FW',
             'VE__POINTED_DURATION_FULL',
             'VE__POINTED_DURATION',
             'VE__POINTED_IMAGE_DT',
             'VE__POINTED_ALONG_OVERLAP_MIN',
             'VE__POINTED_ALONG_OVERLAP',
             'VE__POINTED_ALONG_OFFSET',
             'VE__POINTED_ACROSS_OVERLAP_MIN',
             'VE__POINTED_ACROSS_OVERLAP',
             'VE__POINTED_ACROSS_OFFSET',
             'VE__POINTED_POINTING_DT',
             'VE__OCTIME_DURATION_FULL',
             'VE__SSR_VE',
             'VE__SSR_N_IM',
             'VE__SSR_HS_RATE',
             'VE__SSR_HS_BIT',
             'VE__SSR_HS_SECTORS',
             'VE__SSR_HS_CLUSTERS',
             'VE__SSR_HS_GBIT',
             'VE__SSR_LS_RATE',
             'VE__SSR_LS_PREV_VISIT_NAME',
             'VE__SSR_GBIT',
             'VE__SSR_CUMUL_GBIT',
             'VE__SSR_SSR1',
             'VE__SSR_SSR2',
             'VE__SSR_HS_GBIT1',
             'VE__SSR_HS_GBIT2',
             'VE__SSR_GBIT1',
             'VE__SSR_GBIT2',
             'VE__SSR_CUMUL_GBIT1',
             'VE__SSR_CUMUL_GBIT2',
             'VE__RE_SETUP_1SIDE',
             'VE__RE_SETUP_SSR_1SIDE',
             'VE__RE_OFFSET',
             'VE__RE_DURATION_1SIDE',
             'VE__RE_WRAPUP_1SIDE',
             "ENDOFFILE"]       ## IMPORTANT!! THE END OF THE FILE HAS AN EXTRA PIPE, LIKE THERE IS AN EXTRA EMPTY COLUMN. SCREWS IT ALL UP

visitRates = {"X_PEPSSI_RATE_INCREASE_021":100,
                "X_SWAP_Daily_ON_022":32,
                }










